# Your Solution
version: '3'
services:

  book_catalog:
    image: book_catalog
    build: 
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book_catalog
    ports:
      - "4001:80"
    environment:
      - DATABASE_URL=postgresql://joe_cin_ng_sit722_part_4_user:vdxglUaH0qc6jeMRfXGF3pw8e6JOL2bo@dpg-crg5fbjqf0us73dhkuo0-a.oregon-postgres.render.com/joe_cin_ng_sit722_part_4

  inventory_management:
    image: inventory_management
    build: 
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory_management
    ports:
      - "4002:80"
    environment:
      - DATABASE_URL=postgresql://joe_cin_ng_sit722_part_4_user:vdxglUaH0qc6jeMRfXGF3pw8e6JOL2bo@dpg-crg5fbjqf0us73dhkuo0-a.oregon-postgres.render.com/joe_cin_ng_sit722_part_4
